"use client";
import {useEffect,useState} from "react";
import {createClient} from "@supabase/supabase-js";
type Product={id:string;name:string;category:string;price:string;image:string;description:string;affiliate_url:string};
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
export default function Home(){
 const [products,setProducts]=useState<Product[]>([]);
 useEffect(()=>{supabase.from("products").select("*").eq("published",true).order("created_at",{ascending:false}).then(({data})=>setProducts(data||[]))},[]);
 return <main><nav className="nav"><div className="brand"><span className="brandMark">V</span><span>Veylola Finds</span></div><a className="navCta" href="#deals">Explore deals</a></nav>
 <section className="hero"><div className="heroCopy"><div className="eyebrow">CURATED FINDS • SMART SHOPPING</div><h1>Discover products<br/><span>worth clicking.</span></h1><p>Useful, stylish and trending finds in one simple place.</p><div className="heroActions"><a className="primary" href="#deals">Browse featured finds →</a></div></div><div className="heroCard"><div className="dealBadge">LIVE STORE</div><div className="heroIcon">🛍️</div><strong>New finds every week</strong><span>Shop through our AliExpress affiliate links.</span></div></section>
 <section id="deals" className="deals"><div className="sectionHead"><div><p className="sectionEyebrow">EDITOR'S PICKS</p><h2>Trending finds</h2></div><span className="smallNote">Prices may change on AliExpress.</span></div><div className="grid">{products.map(p=><article className="product" key={p.id}><div className="imageWrap"><img src={p.image} alt={p.name}/><span className="tag">{p.category}</span></div><div className="productBody"><h3>{p.name}</h3><p>{p.description}</p><div className="productFoot"><strong>{p.price}</strong><a href={p.affiliate_url} target="_blank" rel="nofollow sponsored noopener">View deal ↗</a></div></div></article>)}</div>{!products.length&&<div className="empty">No products published yet. Check back soon.</div>}</section>
 <section className="disclosure"><strong>Affiliate disclosure</strong><p>Some links on Veylola Finds are affiliate links. If you buy through one, we may earn a commission at no extra cost to you.</p></section><footer>Veylola Finds © 2026</footer></main>}