"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@supabase/supabase-js";

type Product={id:string;name:string;category:string;price:string;image:string;description:string;affiliate_url:string};
type Category={id:string;name:string;image_url:string;description:string;featured:boolean;active:boolean;sort_order:number};
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"",process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||"");

export default function Home(){
 const [products,setProducts]=useState<Product[]>([]),[categories,setCategories]=useState<Category[]>([]),[query,setQuery]=useState(""),[category,setCategory]=useState("All"),[cart,setCart]=useState<Product[]>([]),[loading,setLoading]=useState(true),[viewer,setViewer]=useState<Product|null>(null),[viewerIndex,setViewerIndex]=useState(0);
 useEffect(()=>{const saved=localStorage.getItem("veylola-cart");if(saved)try{setCart(JSON.parse(saved))}catch{};(async()=>{const [{data:p},{data:c}]=await Promise.all([supabase.from("products").select("*").eq("published",true).order("created_at",{ascending:false}),supabase.from("categories").select("*").eq("active",true).order("sort_order",{ascending:true})]);setProducts((p||[]) as Product[]);setCategories((c||[]) as Category[]);setLoading(false)})()},[]);
 useEffect(()=>localStorage.setItem("veylola-cart",JSON.stringify(cart)),[cart]);\n useEffect(()=>{if(!viewer)return;const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setViewer(null);if(e.key==="ArrowLeft")setViewerIndex(i=>Math.max(0,i-1));if(e.key==="ArrowRight"&&viewer)setViewerIndex(i=>Math.min(imageUrls(viewer.image).length-1,i+1))};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[viewer]);\n function imageUrls(value:string){return value.split(/[,\\n]/).map(x=>x.trim()).filter(Boolean)}
 const names=["All",...categories.map(c=>c.name)]; const featured=categories.filter(c=>c.featured);
 const filtered=useMemo(()=>products.filter(p=>{const ok=category==="All"||p.category===category;const q=query.toLowerCase().trim();return ok&&(!q||[p.name,p.category,p.description].join(" ").toLowerCase().includes(q))}),[products,query,category]);
 function addToCart(p:Product){setCart(c=>c.some(x=>x.id===p.id)?c:[...c,p])} function removeFromCart(id:string){setCart(c=>c.filter(x=>x.id!==id))}
 return <main>
 <nav className="nav"><a className="brand" href="#"><span className="mark">V</span><span>Veylola</span></a><div className="navActions"><a href="#deals">Shop</a><a href="#categories">Categories</a><a href="#about">About</a><button className="cartBtn" onClick={()=>document.getElementById("cart")?.scrollIntoView({behavior:"smooth"})}>Cart ({cart.length})</button></div></nav>
 <section className="hero"><div><small>CURATED FINDS • SMART SHOPPING</small><h1>Discover products<br/><span>worth clicking.</span></h1><p>Useful, stylish and trending finds selected for the Veylola community.</p><a className="primary" href="#deals">Explore products →</a></div><div className="heroBox"><div className="heroIcon">✦</div><strong>Fresh finds, one place.</strong><span>Discover products and follow the deal link when you're ready to buy.</span></div></section>
 <section id="categories" className="categorySection"><div className="sectionTitle"><div><small>SHOP BY CATEGORY</small><h2>Best Selected</h2></div><span>Chosen from Admin</span></div><div className="categoryGrid">{featured.map(c=><button key={c.id} className="categoryCard" onClick={()=>{setCategory(c.name);document.getElementById("deals")?.scrollIntoView({behavior:"smooth"})}}>{c.image_url?<img src={c.image_url} alt=""/>:<div className="categoryPlaceholder">✦</div>}<span>{c.name}</span></button>)}</div></section>
 <section id="deals" className="deals"><div className="head"><div><small>VEYLOLA SHOP</small><h2>Featured finds</h2></div><span>{products.length} published product{products.length===1?"":"s"}</span></div><div className="toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products..." aria-label="Search products"/><div className="chips">{names.map(c=><button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)}>{c}</button>)}</div></div>{loading?<div className="empty">Loading products…</div>:!filtered.length?<div className="empty"><strong>No products found.</strong><span>Try another category or search.</span></div>:<div className="grid">{filtered.map(p=><article className="card" key={p.id}><div className="pic" onClick={()=>{setViewer(p);setViewerIndex(0)}} role="button" tabIndex={0} aria-label={"View all images of "+p.name}>{p.image?<img src={imageUrls(p.image)[0]} alt={p.name} loading="lazy"/>:<div className="noImage">Veylola</div>}<b>{p.category}</b>{imageUrls(p.image).length>1&&<span className="imageCount">▧ {imageUrls(p.image).length}</span>}</div><div className="body"><h3>{p.name}</h3><p>{p.description}</p><div className="foot"><strong>{p.price}</strong><button onClick={()=>addToCart(p)}>{cart.some(x=>x.id===p.id)?"Added ✓":"Add to cart"}</button></div><a className="deal" href={p.affiliate_url} target="_blank" rel="nofollow sponsored noopener">View deal ↗</a></div></article>)}</div>}</section>
 {viewer&&<div className="imageViewer" role="dialog" aria-modal="true" onClick={()=>setViewer(null)}><div className="viewerInner" onClick={e=>e.stopPropagation()}><button className="viewerClose" onClick={()=>setViewer(null)} aria-label="Close">×</button><button className="viewerArrow left" disabled={viewerIndex===0} onClick={()=>setViewerIndex(i=>Math.max(0,i-1))}>‹</button><img className="viewerImage" src={imageUrls(viewer.image)[viewerIndex]} alt={viewer.name+" image "+(viewerIndex+1)}/><button className="viewerArrow right" disabled={viewerIndex>=imageUrls(viewer.image).length-1} onClick={()=>setViewerIndex(i=>Math.min(imageUrls(viewer.image).length-1,i+1))}>›</button><div className="viewerBottom"><strong>{viewer.name}</strong><span>{viewerIndex+1} / {imageUrls(viewer.image).length}</span><div className="viewerThumbs">{imageUrls(viewer.image).map((src,i)=><button key={src+i} className={i===viewerIndex?"selected":""} onClick={()=>setViewerIndex(i)}><img src={src} alt=""/></button>)}</div></div></div></div>}\n <section id="cart" className="cartSection"><div><small>YOUR PICKS</small><h2>Shopping list</h2></div>{!cart.length?<p className="muted">Your cart is empty. Add products above.</p>:<div className="cartList">{cart.map(p=><div className="cartItem" key={p.id}><span>{p.name}</span><strong>{p.price}</strong><button onClick={()=>removeFromCart(p.id)}>Remove</button></div>)}<p className="muted">Veylola uses affiliate deal links. Checkout and payment are completed on the linked merchant site.</p></div>}</section>
 <section id="about" className="notice"><strong>Affiliate disclosure</strong><p>Some Veylola links are affiliate links. We may earn a commission if you purchase through them, at no extra cost to you. Prices and availability can change on the merchant site.</p></section><footer>Veylola © {new Date().getFullYear()} • Smart shopping, simply.</footer>
 </main>
}